[package]
name = "catenis_api_client"
description = "Catenis API client library for the Rust programming language"
version = "0.1.0"
authors = ["Cláudio Sá de Castro <claudio@hiades.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
reqwest = { version = "0.10.8", features = ["blocking", "json", "gzip"] }
url = "2.2.0"
tokio-tungstenite = "0.11.0"
bitcoin_hashes = "0.9.4"
time = "0.2.22"
flate2 = "1.0.19"

[dev-dependencies]
futures = "0.3.7"